<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__ . '/src')
    ->in(__DIR__ . '/tests');

return (new PhpCsFixer\Config())
    ->setRules([
                    // Brace spacing and positioning
                    'braces' => [
                        'allow_single_line_closure' => true,
                        'position_after_functions_and_oop_constructs' => 'next',
                        'position_after_control_structures' => 'same',
                        'position_after_anonymous_constructs' => 'same',
                    ],
                    // Handle elseif formatting
                    'elseif' => true,
                    // Handle long function parameters
                    'method_argument_space' => [
                        'on_multiline' => 'ensure_fully_multiline',
                        'keep_multiple_spaces_after_comma' => false,
                        'after_heredoc' => false,
                    ],
                    // Function declaration formatting for long parameter lists
                    'function_declaration' => [
                        'closure_function_spacing' => 'one',
                        'closure_fn_spacing' => 'none',
                    ],
                    // Symfony-specific rules - disable Yoda style
                    'yoda_style' => [
                        'equal' => false,
                        'identical' => false,
                        'less_and_greater' => false,
                    ],
                    // Concat spacing (spaces around concat operator for PSR12 compatibility)
                    // This overrides Symfony's 'none' spacing to maintain PSR12 compliance
                    'concat_space' => ['spacing' => 'one'],
                    // PHPDoc improvements - comprehensive docblock handling
                    'phpdoc_add_missing_param_annotation' => ['only_untyped' => false],
                    'phpdoc_param_order' => true,
                    'general_phpdoc_annotation_remove' => ['annotations' => ['author', 'package', 'subpackage']],
                    // Function arguments formatting
                    'method_argument_space' => [
                        'on_multiline' => 'ignore',
                        'keep_multiple_spaces_after_comma' => false,
                        'after_heredoc' => false,
                    ],
                    // Force single-line function declarations where possible
                    'single_line_comment_style' => ['comment_types' => ['hash']],
                    // Missing return type annotations
                    'phpdoc_return_self_reference' => ['replacements' => ['this' => '$this', '@this' => '$this', '$self' => 'self', '@self' => 'self', '$static' => 'static', '@static' => 'static']],
                   'yoda_style' => false,
                   'concat_space' => false,
                   'cast_spaces' => false,
                   'array_syntax' => ['syntax' => 'short'],
                   'single_line_comment_style' => true,
                   'line_ending' => true,
                   'binary_operator_spaces' => true,
                   'method_argument_space' => ['on_multiline' => 'ensure_fully_multiline'],
                   'single_line_throw' => false,
                   'ordered_class_elements' => [
                        'order' => [
                            'property_public',
                            'property_protected',
                            'property_private',
                            'method_public',
                            'method_protected',
                            'method_private',
                        ],
                        'sort_algorithm' => 'none',
                    ],
                   'phpdoc_add_missing_param_annotation' => true,
                   'function_declaration' => ['closure_fn_spacing' => 'none'],
                   'concat_space' => ['spacing' => 'one'],
                   'object_operator_without_whitespace' => true,
                   'operator_linebreak' => ['only_booleans' => true],
                   'phpdoc_align' => ['align' => 'left'],
                   'phpdoc_annotation_without_dot' => true,
                   'phpdoc_indent' => true,
                   'phpdoc_inline_tag_normalizer' => true,
                   'phpdoc_no_access' => true,
                   'phpdoc_no_alias_tag' => true,
                   'phpdoc_no_empty_return' => true,
                   'phpdoc_no_package' => true,
                   'phpdoc_no_useless_inheritdoc' => true,
                   'phpdoc_order' => true,
                   'phpdoc_return_self_reference' => true,
                   'phpdoc_scalar' => true,
                   'phpdoc_separation' => true,
                   'phpdoc_single_line_var_spacing' => true,
                   'phpdoc_summary' => true,
                   'phpdoc_tag_casing' => ['tags' => ['inheritDoc']],
                   'phpdoc_tag_type' => ['tags' => ['inheritDoc' => 'annotation']],
                   'phpdoc_to_comment' => true,
                   'phpdoc_trim' => true,
                   'phpdoc_trim_consecutive_blank_line_separation' => true,
                   'phpdoc_types' => true,
                   'phpdoc_types_order' => ['null_adjustment' => 'always_last', 'sort_algorithm' => 'none'],
                   'phpdoc_var_without_name' => true,
                   'linebreak_after_opening_tag' => true,
                   'magic_method_casing' => true,
                   'magic_constant_casing' => true,
                   'native_function_casing' => true,
                   'no_alias_language_construct_call' => true,
                   'no_alternative_syntax' => true,
                   'no_binary_string' => true,
                   'no_blank_lines_after_class_opening' => true,
                   'no_blank_lines_after_phpdoc' => true,
                   'no_break_comment' => true,
                   'no_closing_tag' => true,
                   'no_empty_comment' => true,
                   'no_empty_phpdoc' => true,
                   'no_empty_statement' => true,
                   'no_extra_blank_lines' => ['tokens' => ['break', 'continue', 'extra', 'return', 'throw', 'use', 'parenthesis_brace_block', 'square_brace_block', 'curly_brace_block']],
                   'no_leading_import_slash' => true,
                   'no_leading_namespace_whitespace' => true,
                   'no_mixed_echo_print' => ['use' => 'echo'],
                   'no_multiline_whitespace_around_double_arrow' => true,
                   'multiline_whitespace_before_semicolons' => ['strategy' => 'no_multi_line'],
                   'no_null_property_initialization' => true,
                   'no_short_bool_cast' => true,
                   'no_singleline_whitespace_before_semicolons' => true,
                   'no_superfluous_elseif' => true,
                   'no_superfluous_phpdoc_tags' => ['allow_mixed' => true, 'allow_unused_params' => true, 'allow_unused_params' => true],
                   'no_trailing_comma_in_singleline' => true,
                   'no_unneeded_control_parentheses' => ['statements' => ['break', 'clone', 'continue', 'echo_print', 'return', 'switch_case', 'yield', 'yield_from']],
                   'no_unneeded_curly_braces' => ['namespaces' => true],
                   'no_unset_cast' => true,
                   'no_unused_imports' => true,
                   'no_useless_else' => true,
                   'no_useless_return' => true,
                   'no_whitespace_before_comma_in_array' => true,
                   'no_whitespace_in_blank_line' => true,
                   'normalize_index_brace' => true,
                   'not_operator_with_space' => false,
                   'not_operator_with_successor_space' => false,
                   'object_operator_without_whitespace' => true,
                   'ordered_imports' => ['sort_algorithm' => 'alpha', 'imports_order' => ['class', 'function', 'const']],
                   'php_unit_fqcn_annotation' => true,
                   'php_unit_internal_class' => ['types' => ['normal', 'final', 'abstract']],
                   'php_unit_method_casing' => ['case' => 'camel_case'],
                   'php_unit_size_class' => ['group' => 'small'],
                   'php_unit_test_class_requires_covers' => false,
                   'phpdoc_add_missing_param_annotation' => ['only_untyped' => true],
                   'phpdoc_var_annotation_correct_order' => true,
                   'protected_to_private' => true,
                   'return_type_declaration' => ['space_before' => 'none'],
                   'self_static_accessor' => true,
                   'semicolon_after_instruction' => true,
                   'short_scalar_cast' => true,
                   'simple_to_complex_string_variable' => true,
                   'simplified_if_return' => true,
                   'simplified_null_return' => false,
                   'single_blank_line_at_eof' => true,
                   'single_class_element_per_statement' => ['elements' => ['property', 'const']],
                   'single_import_per_statement' => true,
                   'single_line_after_imports' => true,
                   'single_line_comment_style' => ['comment_types' => ['hash']],
                   'single_quote' => true,
                   'single_space_after_construct' => ['constructs' => ['abstract', 'as', 'attribute', 'break', 'case', 'catch', 'class', 'clone', 'comment', 'const', 'const_import', 'continue', 'do', 'echo', 'else', 'elseif', 'enum', 'extends', 'final', 'finally', 'for', 'foreach', 'function', 'function_import', 'global', 'goto', 'if', 'implements', 'include', 'include_once', 'instanceof', 'insteadof', 'interface', 'match', 'named_argument', 'namespace', 'new', 'open_tag_with_echo', 'php_open', 'print', 'private', 'protected', 'public', 'require', 'require_once', 'return', 'static', 'switch', 'throw', 'trait', 'try', 'type_colon', 'use', 'use_lambda', 'use_trait', 'var', 'while', 'yield', 'yield_from']],
                   'single_trait_insert_per_statement' => true,
                   'space_after_semicolon' => true,
                   'standardize_increment' => true,
                   'standardize_not_equals' => true,
                   'statement_indentation' => true,
                   'switch_case_semicolon_to_colon' => true,
                   'switch_case_space' => true,
                   'switch_continue_to_break' => true,
                   'ternary_operator_spaces' => true,
                   'ternary_to_null_coalescing' => true,
                   'trailing_comma_in_multiline' => ['elements' => ['arrays', 'arguments', 'parameters']],
                   'trim_array_spaces' => true,
                   'types_spaces' => ['space' => 'single', 'space_multiple_catch' => 'single'],
                   'unary_operator_spaces' => true,
                   'visibility_required' => ['elements' => ['property', 'method', 'const']],
                   'whitespace_after_comma_in_array' => true,
                   'yoda_style' => ['equal' => false, 'identical' => false, 'less_and_greater' => false],
               ])
    ->setFinder($finder)
    ->setCacheFile('.php-cs-fixer.cache') // forward compatibility with 3.x line
    ;
